export const knownTechs = [
  'JavaScript',
  'TypeScript',
  'React',
  'React.js',
  'Next.js',
  'Nextjs',
  'Redux',
  'Node.js',
  'Express',
  'Nest.js',
  'Nestjs',
  'Tailwind CSS',
  'Bootstrap',
  'Apollo',
  'Apollo GraphQL',
  'MaterialUI',
  'Ant Design',
  'PrimeReact',
  'PostCSS',
  'Webpack',
  'Vite',
  'Jest',
  'Playwright',
  'Redis',
  'PostgreSQL',
  'MySQL',
  'Oracle',
  'MongoDB',
  'Amazon DocumentDB',
  'Figma',
  'Animations',
  'Tanstack',
  'React Query',
  'SWR',
  'PWA',
  'REST',
  'GraphQL',
  'MVC',
  'DDD',
  'Clean Architecture',
  'Event-Driven Architecture',
  'AWS',
  'Vercel',
  'Heroku',
  'SonarQube',
  'Docker',
  'Rancher',
  'GitHub Actions',
  'Bitbucket Pipeline',
  'Sentry',
  'CloudWatch',
  'Google Analytics',
  'Error Handling',
  'Log Monitoring',
  'Cursor',
  'OpenAI',
  'LangChain',
  'LangGraph',
  'LangSmith',
  'Prisma ORM',
  'TailwindCSS',
  'Shadcn',
  'Firebase',
  'CI/CD',
];
